# Generated by Django 3.1 on 2020-08-10 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aboutus', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aboutus',
            options={'verbose_name': 'View Order', 'verbose_name_plural': 'View Orders'},
        ),
        migrations.AddField(
            model_name='aboutus',
            name='ord_status',
            field=models.CharField(default='UR', max_length=150),
        ),
    ]
