# Generated by Django 3.1 on 2020-08-10 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aboutus', '0004_auto_20200810_0650'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutus',
            name='ord_status',
            field=models.CharField(choices=[('PE', 'Pending'), ('CF', 'Confirmed'), ('CL', 'Rejected')], default='Pending', max_length=50),
        ),
    ]
